### ISSUE TITLE
No attribute 'only_county_mode'

### ISSUE THREAD

**Issue by DmytroKhylko** [lqxdd/TRPS_lab4#1]
For following input

3
France 1 4 4 6
Spain 3 1 6 3
Portugal 1 1 2 2
1
Luxembourg 1 1 1 1
2
Netherlands 1 3 2 4
Belgium 1 1 2 2
2
Netherlands 1 1 2 2
Belgium 2 2 4 4
2
Netherlands 1 1 2 2
Belgium 1 4 2 5
0

I've got error for case number 2 ```'Country' object has no attribute 'only_county_mode'```

**Comment by lqxdd** [comment]
fixed
